appVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" .}}
  lables:
    app: flask-app
spec:
  #LoadBalancer type creates an AWS ELB automatically
  type: {{ .Values.Service.type}}
  ports:
    - port: {{ .Values.Service.port }}
      targetPort: {{ .Values.Service.targetPort }}
      protocol: TCP
      name: http
    selector:
      app: flask-app